apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: pnt-quiz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
      - name: node-backend
        image: docker/getting-started 
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: pnt-quiz
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer